services:
  postgres:
    container_name: nestjs-postgres
    image: postgres
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nestjs"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  data:
